import type { Brand, Theme } from './types';

/**
 * Default brand: ClawMama. The mark is the site-header SVG verbatim (the
 * claw-tapered C generated by clawmama scripts/generate-brand-icons.mjs),
 * with color placeholders so each theme can tint it:
 *   {color}  — claw fill (primary accent)
 *   {color2} — satellite dot (secondary accent)
 *   {color3} — dot core (light on dark themes, paper on light themes)
 */
export const DEFAULT_BRAND: Brand = {
  name: 'ClawMama',
  domain: 'clawmama.run',
  markSvg:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">' +
    '<path d="M35.45 34.45L35.22 35L35 35.59L34.78 36.2L34.53 36.81L34.26 37.42L33.96 38.02L33.62 38.62L33.26 39.21L32.86 39.78L32.43 40.33L31.96 40.85L31.46 41.35L30.93 41.82L30.38 42.26L29.79 42.65L29.18 43.01L28.54 43.32L27.88 43.58L27.21 43.79L26.52 43.94A20.25 20.25 0 1 1 26.52 4.06L27.21 4.21L27.88 4.42L28.54 4.68L29.18 4.99L29.79 5.35L30.38 5.74L30.93 6.18L31.46 6.65L31.96 7.15L32.43 7.67L32.86 8.22L33.26 8.79L33.62 9.38L33.96 9.98L34.26 10.58L34.53 11.19L34.78 11.8L35 12.41L35.22 13L35.45 13.55L34.94 13.25L34.38 13.01L33.8 12.82L33.22 12.65L32.63 12.52L32.05 12.41L31.48 12.33L30.92 12.26L30.36 12.22L29.82 12.18L29.3 12.16L28.78 12.14L28.28 12.13L27.8 12.12L27.33 12.11L26.87 12.1L26.42 12.08L25.98 12.05L25.55 12L25.13 11.94A12.25 12.25 0 1 0 25.13 36.06L25.55 36L25.98 35.95L26.42 35.92L26.87 35.9L27.33 35.89L27.8 35.88L28.28 35.87L28.78 35.86L29.3 35.84L29.82 35.82L30.36 35.78L30.92 35.74L31.48 35.67L32.05 35.59L32.63 35.48L33.22 35.35L33.8 35.18L34.38 34.99L34.94 34.75L35.45 34.45Z" fill="{color}"/>' +
    '<circle cx="39.6" cy="24" r="5.6" fill="{color2}"/>' +
    '<circle cx="39.6" cy="24" r="2.6" fill="{color3}"/>' +
    '</svg>',
};

export function resolveBrand(partial?: Partial<Brand>): Brand {
  if (!partial) return DEFAULT_BRAND;
  // A renamed brand must not inherit the ClawMama mark: without an explicit
  // markSvg it renders wordmark-only.
  const renamed = partial.name !== undefined && partial.name !== DEFAULT_BRAND.name;
  const markSvg = partial.markSvg !== undefined ? partial.markSvg : renamed ? undefined : DEFAULT_BRAND.markSvg;
  return {
    name: partial.name ?? DEFAULT_BRAND.name,
    domain: partial.domain ?? DEFAULT_BRAND.domain,
    ...(markSvg ? { markSvg } : {}),
  };
}

/**
 * Resolves the mark SVG against the theme and returns it as a data URI for a
 * satori <img> node. A custom markSvg without placeholders is used verbatim.
 */
export function markDataUri(brand: Brand, theme: Theme, primary?: string): string | null {
  if (!brand.markSvg) return null;
  const svg = brand.markSvg
    .split('{color2}').join(theme.brand2)
    .split('{color3}').join(theme.mode === 'dark' ? theme.text : theme.surface)
    .split('{color}').join(primary ?? theme.brand);
  return `data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}`;
}
